export type AllLinksStartQuiz =
	| '/lessons/kitchen-utensils/quiz'
	| '/lessons/bedroom/quiz'
	| '/lessons/bathroom/quiz'
	| '/lessons/livingroom/quiz'
	| '/lessons/kitchen/quiz'
	| '/lessons/garden/quiz'
	| '/lessons/clothes/quiz'
	| '/lessons/cleaning/quiz'
	| '/lessons/emotions/quiz'
	| '/lessons/sensations/quiz'
	| '/lessons/vegetables/quiz'
	| '/lessons/fruits/quiz'
	| '/lessons/weather/quiz'
	| '/lessons/weather-advanced/quiz';
